fix primer filter

diff --git a/discoAnt_main b/discoAnt_main
--- a/discoAnt_main
+++ b/discoAnt_main
@@ -262,11 +262,14 @@ function primer_site_function() {
 		echo "Filtering based on primer BED files..."
 		# used to be a 5bp window created around primers, do we need this..?
 		
-		# write out isoforms which do match primers
-		bedtools intersect -wa -u -a $OUTPUT_NAME/temp_files/${OUTPUT_NAME}_isoforms_count_1.gtf -b $forward_primers | bedtools intersect -wa -a - -b $reverse_primers > $OUTPUT_NAME/temp_files/${OUTPUT_NAME}_isoforms_pass1.gtf
-
-		cat $OUTPUT_NAME/temp_files/${OUTPUT_NAME}_isoforms_pass1.gtf | awk '{ if ($3 == "transcript") print $12 }' | sed 's/"//g' | sed 's/;//g' > $OUTPUT_NAME/temp_files/updated_transcriptome.txt
+		# intersect primers with GTF
+		bedtools intersect -wa -u -a $OUTPUT_NAME/temp_files/${OUTPUT_NAME}_isoforms_count_1.gtf -b $forward_primers | bedtools intersect -wa -a - -b $reverse_primers > $OUTPUT_NAME/temp_files/${OUTPUT_NAME}_isoforms_pass1_primer.gtf
+		# write list of transcripts that match primers
+		cat $OUTPUT_NAME/temp_files/${OUTPUT_NAME}_isoforms_pass1_primer.gtf | awk '{ if ($3 == "transcript") print $12 }' | sed 's/"//g' | sed 's/;//g' > $OUTPUT_NAME/temp_files/updated_transcriptome.txt
 		
+		# subset GTF that passed counts filtering with new list of transcripts that match primers
+		cat $OUTPUT_NAME/temp_files/${OUTPUT_NAME}_isoforms_count_1.gtf | grep -wf $OUTPUT_NAME/temp_files/updated_transcriptome.txt > $OUTPUT_NAME/temp_files/${OUTPUT_NAME}_isoforms_pass1.gtf
+
 		if [ -e "$OUTPUT_NAME/temp_files/updated_transcriptome.txt" ]
 		then 	
 			if [ -s "$OUTPUT_NAME/temp_files/updated_transcriptome.txt" ]
@@ -350,6 +353,38 @@ function remapping_function() {
 	done
 
 	
+	if [ -d "$OUTPUT_NAME/salmon_quants" ]
+  	then
+		if [ "$(ls -A $OUTPUT_NAME/salmon_quants)" ] 
+		then
+     		:
+		else
+    		echo "Failed to quantify with salmon, check logs file"
+			exit 1
+		fi
+ 	else
+		echo "Failed to quantify with salmon, check logs file"
+		exit 1
+  	fi
+
+}
+
+function remapping_function_original() {
+	echo "Mapping reads..."
+	running_salmon() {
+		for filename in $path_to_reads/*.fa
+		do
+
+			base=$(basename $filename)
+			sample_reads="${base%.*}"
+			
+			salmon quant --quiet -i $OUTPUT_NAME/updated_transcriptome -l A -r $path_to_reads/${sample_reads}.fa -o $OUTPUT_NAME/salmon_quants/${sample_reads}
+
+		done
+	}
+
+	redirect_output running_salmon
+		
 	if [ -d "$OUTPUT_NAME/salmon_quants" ]
   	then
 		if [ "$(ls -A $OUTPUT_NAME/salmon_quants)" ] 
@@ -473,14 +508,13 @@ downsampling_function
 
 ########## 1. Aligning sample fasta files to reference genome ##########
 
-#### run mapping and suppress output
+# run minimap2
 mapping_genome_function
 
 
 ########## 2.a. Correcting and collapsing transcripts with bambu ##########
 
-# suppressing output here breaks it for some reason...
-##### if suppressed it breaks the primer_site_function part
+# run bambu in R
 run_bambu_function
 
 
@@ -499,7 +533,11 @@ create_metatranscriptome
 ########## 2.c. Re-aligning and quantifying filtered bambu transcripts  ##########
 
 # remap to salmon metatranscriptome
+
+# new, remaps to transcriptome
 remapping_function
+# old, uses salmon in mapping mode
+#remapping_function_original
 
 
 ########## 2.d. Generating count matrix   ##########
